services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: xss2-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: xss2-backend
    environment:
      FLASK_ENV: development
    ports:
      - "3001:3001"
    depends_on:
      - database

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: xss2-database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: xss2
    ports:
      - "3306:3306"