services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mitm-server
    ports:
      - "3000:3000"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: mitm-client
    depends_on:
      - server